# Generated by Django 5.2.1 on 2025-09-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='pending_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
