# Generated by Django 5.2.1 on 2025-09-12 20:31

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_bookmark_pending_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('url'), name='uniq_lower_url', violation_error_message='URL already submitted'),
        ),
    ]
